name: odata_client
version: 0.0.1

author: Sergey A. Chebotarev <sachebotarev@gmail.com>
description: Odata client
homepage: https://github.com/sachebotarev

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  xml: ^3.7.0
  http: ^0.12.0+4
  logger: ^0.8.3
dev_dependencies:
  test: ^1.9.0